package com.antempire


rule "log new cell inserted"
    when
        $c : Cell()
    then
        System.out.println("Cell inserted: " + $c);
end

rule "log new ant inserted"
    when
        $a : Ant()
    then
        System.out.println("Ant inserted: " + $a);
end

rule "start production when inserting an ant"
    when
        $a: Ant()
        $c : Cell(ant == $a)
    then
        System.out.println("Ant: " + $a + " set to cell: " + $c);
        modify($c) {
            setProducing(true);
        }
end

rule "alert producing cell"
    when
        $c : Cell(producing == true)
    then
        System.out.println("Cell producing: " + $c);
end