package com.antempire


rule "log new cell inserted"
    when
        $c : Cell()
    then
        System.out.println("Cell inserted: " + $c);
end

rule "log new ant inserted"
    when
        $a : Ant()
    then
        System.out.println("Ant inserted: " + $a);
end

rule "start production when inserting an ant"
    when
        $a: Ant()
        $c : Cell(ant == $a)
    then
        System.out.println("Ant: " + $a + " set to cell: " + $c);
        modify($c) {
            setProducing(true);
        }
end

rule "stop production when two adjacent queen"
    when
        $c1 : Cell($x1: x , $y1 : y, ant!.queen)
        $c2 : Cell(x == $x1 - 1, y == $y1, ant!.queen)
    then
        System.out.println("Two adjacent queens: " + $c1 + " " + $c2);
        modify($c1) {
            setProducing(false);
        }
        modify($c2) {
            setProducing(false);
        }
end

rule "alert producing cell"
    when
        $c : Cell(producing == true)
    then
        System.out.println("Cell producing: " + $c);
end